language: php
php:
  - "nightly"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

env:
  - DOKUWIKI=TestRequest
before_install: wget https://raw.github.com/lisps/dokuwiki-travis/master/travis.sh
install: sh travis.sh
script: cd _test && phpunit --stderr --group plugin_sneakyindexfix
